import { Injectable } from '@nestjs/common';
import * as crypto from 'crypto';
import { SecretManagerService } from './secret-manager.service';

@Injectable()
export class CryptoService {
  private readonly algorithm = 'aes-256-gcm';
  private readonly key: Buffer;

  constructor(private readonly secretManager: SecretManagerService) {
    const hexKey = this.secretManager.get('ENCRYPTION_MASTER_KEY');
    this.key = Buffer.from(hexKey, 'hex');
    if (this.key.length !== 32) {
      throw new Error(
        'ENCRYPTION_MASTER_KEY must be exactly 32 bytes (64 hex characters) for aes-256-gcm',
      );
    }
  }

  /**
   * Encrypts a plaintext string into a format suitable for database storage.
   * Format: "iv.authTag.ciphertext" (Base64 encoded)
   */
  encrypt(text: string): string {
    if (!text) return text;

    const iv = crypto.randomBytes(12); // Recommended 12 bytes for GCM
    const cipher = crypto.createCipheriv(this.algorithm, this.key, iv);

    let encrypted = cipher.update(text, 'utf8', 'base64');
    encrypted += cipher.final('base64');

    const authTag = cipher.getAuthTag();

    // Combine parts into a single string: iv(b64).authTag(b64).ciphertext(b64)
    return `${iv.toString('base64')}.${authTag.toString('base64')}.${encrypted}`;
  }

  /**
   * Decrypts a ciphertext generated by this service back to plaintext.
   */
  decrypt(encryptedData: string): string {
    if (!encryptedData) return encryptedData;

    const parts = encryptedData.split('.');
    if (parts.length !== 3) {
      throw new Error('Invalid encrypted data format');
    }

    const [ivBase64, authTagBase64, ciphertext] = parts;
    const iv = Buffer.from(ivBase64, 'base64');
    const authTag = Buffer.from(authTagBase64, 'base64');

    const decipher = crypto.createDecipheriv(this.algorithm, this.key, iv);
    decipher.setAuthTag(authTag);

    let decrypted = decipher.update(ciphertext, 'base64', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
  }

  /**
   * Creates a deterministic hash of the text using HMAC-SHA256.
   * Useful for indexing and searching encrypted fields securely.
   */
  hash(text: string): string {
    if (!text) return text;
    return crypto.createHmac('sha256', this.key).update(text).digest('hex');
  }
}
